//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeHands.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datum
    {
        public int ID { get; set; }
        public double TaxForVisa { get; set; }
        public double Tax { get; set; }
        public int Delivery { get; set; }
        public bool AllowKnownNumber { get; set; }
        public bool AllowVisa { get; set; }
    }
}
