//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeHands.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Provider()
        {
            this.Offers = new HashSet<Offer>();
            this.Products = new HashSet<Product>();
            this.Provider_Rates = new HashSet<Provider_Rates>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string TradeName { get; set; }
        public string Token { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public double Lat { get; set; }
        public double Log { get; set; }
        public string Location { get; set; }
        public bool IsAvaiable { get; set; }
        public bool AllowVisa { get; set; }
        public bool IsExcelent { get; set; }
        public string KnownNumber { get; set; }
        public Nullable<double> Discount { get; set; }
        public int City_ID { get; set; }
        public int Country_ID { get; set; }
        public string Currency { get; set; }
        public bool Admin_Accept { get; set; }
        public string AccountNumber { get; set; }
        public string BankName { get; set; }
        public string IPan { get; set; }
        public string SwiftCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Offer> Offers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Provider_Rates> Provider_Rates { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
    }
}
